#!/usr/bin/env python3
"""
rename_note.py — Rewrite wikilinks across a Foam vault after renaming a note.

This script implements the wikilink sweep required by §N10 / §13.4 of the
vault organization guideline. It does NOT move files — use `git mv` (or the
wrapper script `rename-note.sh`) to move the file itself.

USAGE
    rename_note.py <old-slug> <new-slug> [--apply] [--vault-root PATH]

    Default is dry-run: prints a report of what WOULD change without writing.
    Add --apply to actually rewrite files.

WHAT IT REWRITES (in prose only; code blocks are left alone)
    [[old]]              → [[new]]
    [[old|alias]]        → [[new|alias]]
    [[old#heading]]      → [[new#heading]]
    [[old#heading|alias]]→ [[new#heading|alias]]
    ![[old]]             → ![[new]]
    ![[old|alias]]       → ![[new|alias]]

WHAT IT LEAVES ALONE
  - Fenced code blocks (``` or ~~~)
  - Inline code (`...`)
  - Foam's autogenerated link-reference block at the bottom of files
  - Protected directories (loaded from _meta/config.jsonc at import time):
    .foam, .vscode, attachments, .git, node_modules, _meta
  - Non-matching slugs (e.g. [[oldbar]] is NOT matched by old='old')
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path
from typing import Iterable


# Hard-coded fallback used only if _meta/config.jsonc cannot be loaded
# (e.g., during bootstrap, in a stripped copy of the scripts directory,
# or if the config loader itself is broken). Under normal operation,
# PROTECTED_DIRS is loaded from config.jsonc at import time.
_FALLBACK_PROTECTED_DIRS = frozenset({
    ".foam",
    ".vscode",
    "attachments",
    ".git",
    "node_modules",
    "_meta",
})


def _load_protected_dirs_from_config() -> frozenset[str]:
    """Return protected.directories from _meta/config.jsonc, or the fallback."""
    try:
        # Local import so that tests can run rename_note.py without the
        # config file present. If config_loader is not importable or
        # the file is missing, we fall back.
        sys.path.insert(0, str(Path(__file__).resolve().parents[2] / "lib"))
        from config_loader import load_config  # type: ignore
        cfg = load_config()
        dirs = cfg.get("protected", {}).get("directories")
        if isinstance(dirs, list) and all(isinstance(d, str) for d in dirs):
            return frozenset(dirs)
    except Exception:
        pass
    return _FALLBACK_PROTECTED_DIRS


PROTECTED_DIRS = _load_protected_dirs_from_config()

FOAM_BLOCK_START = '[//begin]: # "Autogenerated link references for markdown compatibility"'
FOAM_BLOCK_END = '[//end]: # "Autogenerated link references"'

FENCE_RE = re.compile(r"^\s{0,3}(```|~~~)")

# One regex to match every wikilink form. Named groups make the rewrite clean.
#   embed:   optional leading "!"
#   target:  slug (no brackets, pipe, or hash)
#   heading: optional "#heading"
#   alias:   optional "|alias"
WIKILINK_RE = re.compile(
    r"(?P<embed>!)?\[\["
    r"(?P<target>[^\[\]\|#]+)"
    r"(?:#(?P<heading>[^\[\]\|]+))?"
    r"(?:\|(?P<alias>[^\[\]]+))?"
    r"\]\]"
)


def iter_markdown_files(vault_root: Path) -> Iterable[Path]:
    """Yield every .md file under vault_root, skipping protected directories."""
    for path in sorted(vault_root.rglob("*.md")):
        rel_parts = path.relative_to(vault_root).parts
        if any(part in PROTECTED_DIRS for part in rel_parts[:-1]):
            continue
        yield path


def rewrite_wikilinks_in_text(text: str, old_slug: str, new_slug: str) -> tuple[str, int]:
    """Rewrite matching wikilinks in a prose fragment. Returns (new_text, count)."""
    count = 0

    def sub(m: re.Match) -> str:
        nonlocal count
        if m.group("target") != old_slug:
            return m.group(0)
        count += 1
        embed = m.group("embed") or ""
        heading = f"#{m.group('heading')}" if m.group("heading") else ""
        alias = f"|{m.group('alias')}" if m.group("alias") else ""
        return f"{embed}[[{new_slug}{heading}{alias}]]"

    new_text = WIKILINK_RE.sub(sub, text)
    return new_text, count


def process_prose_line(line: str, old_slug: str, new_slug: str) -> tuple[str, int]:
    """Rewrite wikilinks on a prose line, skipping inline-code spans."""
    # Split on inline code spans. An inline code span is `...` on a single line.
    # The capturing group preserves the delimiters in the split output.
    segments = re.split(r"(`[^`\n]*`)", line)
    total = 0
    out: list[str] = []
    for seg in segments:
        if seg.startswith("`") and seg.endswith("`") and len(seg) >= 2:
            out.append(seg)  # inline code, untouched
        else:
            new_seg, n = rewrite_wikilinks_in_text(seg, old_slug, new_slug)
            total += n
            out.append(new_seg)
    return "".join(out), total


def process_file_content(content: str, old_slug: str, new_slug: str) -> tuple[str, int]:
    """Rewrite a full file's content. Returns (new_content, total_replacements)."""
    lines = content.split("\n")
    out_lines: list[str] = []
    in_fence = False
    in_foam_block = False
    total = 0

    for line in lines:
        # Foam's autogenerated link-reference block: preserve verbatim.
        if not in_foam_block and line.strip() == FOAM_BLOCK_START:
            in_foam_block = True
            out_lines.append(line)
            continue
        if in_foam_block:
            out_lines.append(line)
            if line.strip() == FOAM_BLOCK_END:
                in_foam_block = False
            continue

        # Fenced code block: toggle on ``` or ~~~ lines, preserve verbatim.
        if FENCE_RE.match(line):
            in_fence = not in_fence
            out_lines.append(line)
            continue
        if in_fence:
            out_lines.append(line)
            continue

        # Prose line: rewrite, but skip inline-code spans.
        new_line, n = process_prose_line(line, old_slug, new_slug)
        total += n
        out_lines.append(new_line)

    return "\n".join(out_lines), total


def validate_slug(slug: str, label: str) -> None:
    """Guideline §N2: [A-Za-z0-9]+(-[A-Za-z0-9]+)*"""
    if not re.fullmatch(r"[A-Za-z0-9]+(-[A-Za-z0-9]+)*", slug):
        sys.exit(
            f"error: {label} slug '{slug}' is not valid per guideline §N2.\n"
            "       Expected: [A-Za-z0-9]+(-[A-Za-z0-9]+)*  (letters, digits, hyphens)"
        )


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Rewrite wikilinks across a Foam vault after renaming a note.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="Default is dry-run. Use --apply to write changes.",
    )
    parser.add_argument("old_slug", help="old note slug (filename without .md)")
    parser.add_argument("new_slug", help="new note slug (filename without .md)")
    parser.add_argument(
        "--apply",
        action="store_true",
        help="actually write changes to disk (default: dry-run)",
    )
    parser.add_argument(
        "--vault-root",
        type=Path,
        default=Path.cwd(),
        help="vault root directory (default: current directory)",
    )
    parser.add_argument(
        "--quiet",
        action="store_true",
        help="suppress per-file output; only print summary",
    )
    args = parser.parse_args()

    validate_slug(args.old_slug, "old")
    validate_slug(args.new_slug, "new")

    if args.old_slug == args.new_slug:
        sys.exit("error: old and new slugs are identical; nothing to do.")

    vault_root = args.vault_root.resolve()
    if not vault_root.is_dir():
        sys.exit(f"error: vault root '{vault_root}' is not a directory.")

    files_scanned = 0
    files_changed = 0
    total_replacements = 0
    changes: list[tuple[Path, int]] = []

    for path in iter_markdown_files(vault_root):
        files_scanned += 1
        try:
            content = path.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            print(f"warning: skipping non-UTF8 file: {path}", file=sys.stderr)
            continue

        new_content, n = process_file_content(content, args.old_slug, args.new_slug)
        if n > 0:
            files_changed += 1
            total_replacements += n
            changes.append((path, n))
            if args.apply:
                path.write_text(new_content, encoding="utf-8")

    mode = "APPLIED" if args.apply else "DRY-RUN"
    print(f"[{mode}] {args.old_slug} -> {args.new_slug}")
    print(f"  scanned: {files_scanned} file(s)")
    print(f"  changed: {files_changed} file(s), {total_replacements} link(s)")

    if not args.quiet and changes:
        print()
        for path, n in changes:
            rel = path.relative_to(vault_root)
            print(f"  {rel}: {n} link(s)")

    if not args.apply and files_changed > 0:
        print("\nDry-run only. Re-run with --apply to write changes.")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
