#!/usr/bin/env python3
"""
Tests for rename_note.py.

Runs 18 cases covering every wikilink form, code-block safety, inline-code
safety, the Foam autogenerated link-reference block, protected directories,
and non-matching slugs.

Usage:
    python3 test_rename_note.py
"""

from __future__ import annotations

import sys
from pathlib import Path
from tempfile import TemporaryDirectory

SCRIPT_DIR = Path(__file__).resolve().parent
META_DIR = SCRIPT_DIR.parents[1]  # _meta/
sys.path.insert(0, str(SCRIPT_DIR))
sys.path.insert(0, str(META_DIR / "lib"))

from rename_note import (  # noqa: E402
    process_file_content,
    iter_markdown_files,
    PROTECTED_DIRS,
)
from config_loader import (  # noqa: E402
    strip_jsonc_comments,
    load_config,
    find_vault_root,
)


# ----- unit tests on process_file_content --------------------------------

CASES: list[tuple[str, str, str, str, int]] = [
    # (name, old, new, input, expected_count)
    (
        "plain wikilink",
        "foo", "bar",
        "See [[foo]] for details.",
        1,
    ),
    (
        "aliased wikilink",
        "foo", "bar",
        "See [[foo|the foo note]] here.",
        1,
    ),
    (
        "heading wikilink",
        "foo", "bar",
        "Jump to [[foo#section-one]] please.",
        1,
    ),
    (
        "heading + alias",
        "foo", "bar",
        "See [[foo#results|results section]].",
        1,
    ),
    (
        "embed",
        "foo", "bar",
        "Here's the note: ![[foo]]",
        1,
    ),
    (
        "embed with alias",
        "foo", "bar",
        "Embed: ![[foo|displayed]]",
        1,
    ),
    (
        "multiple in one line",
        "foo", "bar",
        "[[foo]] and [[foo#a]] and [[foo|x]] on one line.",
        3,
    ),
    (
        "partial slug NOT matched",
        "foo", "bar",
        "[[foobar]] and [[foo-baz]] should NOT change.",
        0,
    ),
    (
        "different slug NOT matched",
        "foo", "bar",
        "[[baz]] and [[qux]] should NOT change.",
        0,
    ),
    (
        "inside fenced code block",
        "foo", "bar",
        "Before.\n```\n[[foo]] in code\n```\nAfter [[foo]].",
        1,  # only the one outside the fence
    ),
    (
        "inside tilde fenced code block",
        "foo", "bar",
        "~~~\n[[foo]]\n~~~\n[[foo]]",
        1,
    ),
    (
        "inside inline code",
        "foo", "bar",
        "Use `[[foo]]` for wikilinks. Real link: [[foo]]",
        1,
    ),
    (
        "inside Foam autogenerated block",
        "foo", "bar",
        (
            "Content with [[foo]].\n\n"
            '[//begin]: # "Autogenerated link references for markdown compatibility"\n'
            '[foo]: foo.md "foo"\n'
            '[//end]: # "Autogenerated link references"\n'
        ),
        1,  # only the prose one, not the autogen block
    ),
    (
        "mixed case preservation",
        "My-Note", "My-Better-Note",
        "See [[My-Note]] and [[My-Note|the note]].",
        2,
    ),
    (
        "case-sensitive NOT matched",
        "My-Note", "My-Better-Note",
        "[[my-note]] should NOT change (different case).",
        0,
    ),
    (
        "empty file",
        "foo", "bar",
        "",
        0,
    ),
    (
        "no wikilinks at all",
        "foo", "bar",
        "# Title\n\nJust prose, no links.",
        0,
    ),
    (
        "nested fence inside prose",
        "foo", "bar",
        "[[foo]]\n```python\nprint('[[foo]]')\n```\n[[foo]]",
        2,  # first and last, but not the one inside the fence
    ),
]


def run_unit_tests() -> tuple[int, int]:
    passed = 0
    failed = 0
    for name, old, new, content, expected in CASES:
        _, count = process_file_content(content, old, new)
        if count == expected:
            passed += 1
            print(f"  PASS  {name}")
        else:
            failed += 1
            print(f"  FAIL  {name}: expected {expected} replacement(s), got {count}")
    return passed, failed


# ----- integration test: exact output for plain case ---------------------

def test_exact_output() -> bool:
    content = (
        "# Title\n\n"
        "See [[foo]] and [[foo|alias]] and [[foo#head]] and [[foo#head|alias2]].\n"
        "Embed: ![[foo]]\n"
    )
    expected = (
        "# Title\n\n"
        "See [[bar]] and [[bar|alias]] and [[bar#head]] and [[bar#head|alias2]].\n"
        "Embed: ![[bar]]\n"
    )
    new_content, _ = process_file_content(content, "foo", "bar")
    if new_content == expected:
        print("  PASS  exact output rewrite")
        return True
    else:
        print("  FAIL  exact output rewrite")
        print("    expected:")
        for line in expected.split("\n"):
            print(f"      {line!r}")
        print("    got:")
        for line in new_content.split("\n"):
            print(f"      {line!r}")
        return False


# ----- integration test: protected directories ---------------------------

def test_protected_dirs() -> bool:
    with TemporaryDirectory() as tmp:
        root = Path(tmp)
        (root / "1-projects").mkdir()
        (root / ".foam" / "templates").mkdir(parents=True)
        (root / ".vscode").mkdir()
        (root / "attachments").mkdir()
        (root / ".git").mkdir()
        (root / "_meta").mkdir()

        (root / "1-projects" / "note.md").write_text("[[foo]]")
        (root / ".foam" / "templates" / "new.md").write_text("[[foo]]")
        (root / ".vscode" / "settings.md").write_text("[[foo]]")
        (root / "attachments" / "readme.md").write_text("[[foo]]")
        (root / ".git" / "HEAD.md").write_text("[[foo]]")
        (root / "_meta" / "notes.md").write_text("[[foo]]")
        (root / "root-note.md").write_text("[[foo]]")

        found = {p.relative_to(root).as_posix() for p in iter_markdown_files(root)}
        expected = {"1-projects/note.md", "root-note.md"}
        if found == expected:
            print("  PASS  protected directory skipping")
            return True
        else:
            print(f"  FAIL  protected dirs: expected {expected}, got {found}")
            return False


# ----- config loader tests ------------------------------------------------

def test_strip_jsonc_line_comments() -> bool:
    text = '{"a": 1, // trailing comment\n"b": 2}'
    expected_after_parse = {"a": 1, "b": 2}
    import json as _json
    try:
        got = _json.loads(strip_jsonc_comments(text))
    except Exception as e:
        print(f"  FAIL  strip line comments: {e}")
        return False
    if got == expected_after_parse:
        print("  PASS  strip line comments")
        return True
    print(f"  FAIL  strip line comments: {got}")
    return False


def test_strip_jsonc_block_comments() -> bool:
    text = '{/* header */ "a": /* inline */ 1, "b": 2 /* tail */}'
    import json as _json
    try:
        got = _json.loads(strip_jsonc_comments(text))
    except Exception as e:
        print(f"  FAIL  strip block comments: {e}")
        return False
    if got == {"a": 1, "b": 2}:
        print("  PASS  strip block comments")
        return True
    print(f"  FAIL  strip block comments: {got}")
    return False


def test_strip_jsonc_preserves_strings() -> bool:
    # String literals that LOOK like comments must not be stripped.
    text = '{"url": "http://example.com", "path": "a/*/b"}'
    import json as _json
    try:
        got = _json.loads(strip_jsonc_comments(text))
    except Exception as e:
        print(f"  FAIL  preserve strings: {e}")
        return False
    if got == {"url": "http://example.com", "path": "a/*/b"}:
        print("  PASS  preserve strings containing // and /*")
        return True
    print(f"  FAIL  preserve strings: {got}")
    return False


def test_config_loads_from_vault() -> bool:
    """Integration: load the actual config.jsonc from the vault."""
    try:
        cfg = load_config()
    except FileNotFoundError:
        print("  SKIP  load real config.jsonc (file not present — bootstrap?)")
        return True  # not a failure during bootstrap
    except Exception as e:
        print(f"  FAIL  load real config.jsonc: {e}")
        return False

    # Structural sanity checks — slim v2.1 schema.
    required_top = {"_self", "protected", "canonical_folders", "naming",
                    "frontmatter", "links", "features", "agent"}
    missing = required_top - set(cfg.keys())
    if missing:
        print(f"  FAIL  config missing top-level keys: {missing}")
        return False

    # protected.directories must contain the canonical minimum set.
    dirs = set(cfg["protected"]["directories"])
    minimum = {".git", ".foam", ".vscode", "_meta"}
    if not minimum.issubset(dirs):
        print(f"  FAIL  protected.directories missing: {minimum - dirs}")
        return False

    # protected.files must include the three root-level protected files.
    # (getting-started.md was removed from this vault in commit 501fb39.)
    files = set(cfg["protected"]["files"])
    expected_files = {"inbox.md", "todo.md"}
    if files != expected_files:
        print(f"  FAIL  protected.files = {files}, expected {expected_files}")
        return False

    print("  PASS  load real config.jsonc with structural checks")
    return True


def test_rename_note_uses_config() -> bool:
    """PROTECTED_DIRS in rename_note.py should reflect config.jsonc when available."""
    try:
        cfg = load_config()
    except FileNotFoundError:
        print("  SKIP  rename_note uses config (bootstrap — no config file)")
        return True
    cfg_dirs = set(cfg["protected"]["directories"])
    if PROTECTED_DIRS == cfg_dirs:
        print("  PASS  rename_note.PROTECTED_DIRS matches config")
        return True
    print(f"  FAIL  rename_note.PROTECTED_DIRS={PROTECTED_DIRS} != config={cfg_dirs}")
    return False


# ----- main runner --------------------------------------------------------

def main() -> int:
    print("rename_note.py + config_loader test suite")
    print("=" * 50)
    print("\nUnit tests (process_file_content):")
    unit_pass, unit_fail = run_unit_tests()

    print("\nIntegration tests (rename_note):")
    exact_ok = test_exact_output()
    dirs_ok = test_protected_dirs()

    print("\nConfig loader tests:")
    cfg_tests = [
        test_strip_jsonc_line_comments(),
        test_strip_jsonc_block_comments(),
        test_strip_jsonc_preserves_strings(),
        test_config_loads_from_vault(),
        test_rename_note_uses_config(),
    ]

    extra_pass = int(exact_ok) + int(dirs_ok) + sum(int(x) for x in cfg_tests)
    extra_fail = (2 + len(cfg_tests)) - extra_pass

    total_pass = unit_pass + extra_pass
    total_fail = unit_fail + extra_fail

    print()
    print("=" * 50)
    print(f"Total: {total_pass} passed, {total_fail} failed")
    return 0 if total_fail == 0 else 1


if __name__ == "__main__":
    raise SystemExit(main())
