#!/usr/bin/env python3
"""
test_vault_check.py — Tests for the read-only vault auditor.

Strategy: for each rule, build a synthetic vault in a tmpdir with the minimum
structure needed (config.jsonc + whatever files trigger or fail the rule), run
vault_check.walk_vault, and assert the expected rule codes appear (or don't).

Stdlib only. Run with:  python3 _meta/scripts/test_vault_check.py
"""
from __future__ import annotations

import shutil
import sys
import tempfile
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(SCRIPT_DIR))
sys.path.insert(0, str(SCRIPT_DIR.parents[1] / "lib"))
import vault_check  # noqa: E402
from config_loader import load_config  # noqa: E402


# --------------------------------------------------------------------------- #
# Fixture helpers
# --------------------------------------------------------------------------- #

MINIMAL_CONFIG_JSONC = """\
// test fixture config
{
  "_self": {"version": "test", "guideline_version": "test", "guideline_path": "_meta/vault-organization-guideline.md", "last_updated": "2026-04-11", "format": "jsonc", "loader": "_meta/scripts/config_loader.py"},
  "protected": {
    "directories": [".git", ".foam", ".vscode",  "attachments", "node_modules", "_meta"],
    "files": ["inbox.md", "todo.md"],
    "regions": {
      "foam_link_references": {
        "start_marker": "[//begin]: # \\"Autogenerated link references for markdown compatibility\\"",
        "end_marker": "[//end]: # \\"Autogenerated link references\\"",
        "managed_by": "Foam",
        "rule": "preserve-verbatim"
      }
    },
    "exceptions": {}
  },
  "canonical_folders": {
    "top_level": ["journal", "1-projects", "2-areas", "3-resources", "4-atlas", "5-cards", "_archive", "_meta"],
    "max_depth": 3,
    "no_other_top_level": true,
    "forbid_single_file_subfolders": true
  },
  "naming": {
    "slug_regex": "^(?![ .])[^/\\\\\\\\:*?\\"<>|\\\\x00-\\\\x1f]+(?<![ .])$",
    "case_preserving": true,
    "case_collision_within_folder": false,
    "file_extension": ".md"
  },
  "frontmatter": {
    "required": ["title", "created"],
    "optional": ["tags", "type"],
    "forbidden": ["status", "folder", "category", "project", "date", "path", "modified"],
    "reserved_prefixes": ["foam_", "_"],
    "created_immutable": true,
    "created_format": "YYYY-MM-DD"
  },
  "tags": {"discovered_by": "foam", "hierarchy_separator": "/", "case_convention": "lowercase"},
  "note_types": {"registry_path": "_meta/note-types.md", "optional": true, "case_convention": "lowercase-hyphenated"},
  "links": {"style": "wikilink", "wikilink_regex": "(?P<embed>!)?\\\\[\\\\[(?P<target>[^\\\\[\\\\]\\\\|#]+)(?:#(?P<heading>[^\\\\[\\\\]\\\\|]+))?(?:\\\\|(?P<alias>[^\\\\[\\\\]]+))?\\\\]\\\\]", "slug_based": true, "global_uniqueness": true, "case_sensitive_resolution": false},
  "scripts": {"rename_note": null, "rename_wrapper": null, "tests": null, "config_loader": null, "vault_check": "_meta/scripts/vault_check.py"},
  "workflow": {"inbox_file": "inbox.md", "daily_note_path_template": "journal/{YYYY}-{MM}-{DD}.md", "capture_always_goes_to": "inbox.md", "tasks_live_in_files": true, "task_syntax": "- [ ]", "task_due_syntax": "due: YYYY-MM-DD"},
  "agent": {
    "read_before_any_work": [],
    "before_any_write": [],
    "before_any_rename": [],
    "before_adding_note_type": [],
    "before_schema_change": [],
    "safety": []
  }
}
"""

GOOD_FRONTMATTER = """---
title: "A good note"
created: 2026-04-11
---

Body.
"""


def make_vault(tmp: Path) -> Path:
    """Build a minimal-but-valid vault at tmp and return its path."""
    root = tmp / "vault"
    root.mkdir()
    # .git marker so find_vault_root() works if called
    (root / ".git").mkdir()
    # _meta layout
    meta = root / "_meta"
    meta.mkdir()
    (meta / "core").mkdir()
    (meta / "core" / "config.jsonc").write_text(MINIMAL_CONFIG_JSONC, encoding="utf-8")
    # Canonical top-level folders, each with a .gitkeep
    for top in ("journal", "1-projects", "2-areas", "3-resources", "4-atlas", "5-cards", "_archive"):
        (root / top).mkdir()
        (root / top / ".gitkeep").write_text("", encoding="utf-8")
    return root


def write_note(path: Path, body: str = GOOD_FRONTMATTER) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(body, encoding="utf-8")


def rules_in(report) -> set[str]:
    return {f.rule for f in report.findings}


def paths_for_rule(report, rule: str) -> list[str]:
    return [f.path for f in report.findings if f.rule == rule]


# --------------------------------------------------------------------------- #
# Tests
# --------------------------------------------------------------------------- #

def test_clean_vault_has_zero_findings():
    with tempfile.TemporaryDirectory() as tmp:
        root = make_vault(Path(tmp))
        cfg = load_config(root)
        write_note(root / "1-projects" / "alpha" / "kickoff-notes.md")
        write_note(root / "2-areas" / "research" / "lab-book.md")
        report = vault_check.walk_vault(root, cfg)
        assert report.errors == [], f"unexpected errors: {[f.format_line() for f in report.errors]}"
        # Warnings allowed (F5 on single-file subfolders) but no errors.


def test_unknown_top_level_folder():
    with tempfile.TemporaryDirectory() as tmp:
        root = make_vault(Path(tmp))
        cfg = load_config(root)
        write_note(root / "random" / "stray-note.md")
        report = vault_check.walk_vault(root, cfg)
        assert "F2" in rules_in(report)


def test_missing_required_frontmatter_key():
    with tempfile.TemporaryDirectory() as tmp:
        root = make_vault(Path(tmp))
        cfg = load_config(root)
        write_note(
            root / "1-projects" / "alpha" / "incomplete.md",
            body="---\ntitle: \"no created key\"\n---\n\nBody.\n",
        )
        report = vault_check.walk_vault(root, cfg)
        m1_paths = paths_for_rule(report, "M1")
        assert any("incomplete.md" in p for p in m1_paths)


def test_missing_frontmatter_block_entirely():
    with tempfile.TemporaryDirectory() as tmp:
        root = make_vault(Path(tmp))
        cfg = load_config(root)
        write_note(
            root / "1-projects" / "alpha" / "raw.md",
            body="# Just a heading, no frontmatter.\n",
        )
        report = vault_check.walk_vault(root, cfg)
        assert "M1" in rules_in(report)


def test_forbidden_frontmatter_key():
    with tempfile.TemporaryDirectory() as tmp:
        root = make_vault(Path(tmp))
        cfg = load_config(root)
        write_note(
            root / "1-projects" / "alpha" / "stale-schema.md",
            body="---\ntitle: \"x\"\ncreated: 2026-04-11\nstatus: active\n---\n",
        )
        report = vault_check.walk_vault(root, cfg)
        m2_paths = paths_for_rule(report, "M2")
        assert any("stale-schema.md" in p for p in m2_paths)


def test_invalid_created_date_format():
    with tempfile.TemporaryDirectory() as tmp:
        root = make_vault(Path(tmp))
        cfg = load_config(root)
        write_note(
            root / "1-projects" / "alpha" / "bad-date.md",
            body="---\ntitle: \"x\"\ncreated: 04/11/2026\n---\n",
        )
        report = vault_check.walk_vault(root, cfg)
        assert "M4" in rules_in(report)


def test_slug_grammar_violation():
    with tempfile.TemporaryDirectory() as tmp:
        root = make_vault(Path(tmp))
        cfg = load_config(root)
        # Per guideline v1.8, only filesystem-illegal chars are rejected.
        # Underscores, spaces, dots, parentheses, etc. are now ALLOWED.
        # A colon is cross-platform illegal and must fail N1.
        write_note(root / "1-projects" / "alpha" / "bad:slug.md")
        report = vault_check.walk_vault(root, cfg)
        assert "N1" in rules_in(report)


def test_permissive_slugs_accepted():
    """Spaces, underscores, dots, parentheses, mixed case are all valid."""
    with tempfile.TemporaryDirectory() as tmp:
        root = make_vault(Path(tmp))
        cfg = load_config(root)
        for name in [
            "ACE inhibitors in CKD.md",
            "meeting_notes.md",
            "IRB-2026-0143 Amendment (final).md",
            "SRMA.Delirium.md",
        ]:
            write_note(root / "1-projects" / "alpha" / name)
        report = vault_check.walk_vault(root, cfg)
        assert "N1" not in rules_in(report)


def test_slug_collision_across_vault():
    with tempfile.TemporaryDirectory() as tmp:
        root = make_vault(Path(tmp))
        cfg = load_config(root)
        write_note(root / "1-projects" / "alpha" / "overlap.md")
        write_note(root / "2-areas" / "research" / "overlap.md")
        report = vault_check.walk_vault(root, cfg)
        assert "L3" in rules_in(report)


def test_case_collision_within_folder_not_triggered_normally():
    with tempfile.TemporaryDirectory() as tmp:
        root = make_vault(Path(tmp))
        cfg = load_config(root)
        write_note(root / "1-projects" / "alpha" / "MixedCase.md")
        write_note(root / "1-projects" / "alpha" / "Other.md")
        report = vault_check.walk_vault(root, cfg)
        assert "N2a" not in rules_in(report)


def test_depth_over_max():
    with tempfile.TemporaryDirectory() as tmp:
        root = make_vault(Path(tmp))
        cfg = load_config(root)
        # max_depth = 3, so parts allowed up to 4 (top + L2 + L3 + filename)
        # Actually: len(parts) <= max_depth + 1 = 4 passes.
        # 1-projects/alpha/beta/gamma/note.md → parts len = 5 → fails.
        deep = root / "1-projects" / "alpha" / "beta" / "gamma" / "too-deep.md"
        write_note(deep)
        report = vault_check.walk_vault(root, cfg)
        assert "F4" in rules_in(report)


def test_protected_directory_is_pruned():
    """Files inside a protected directory are not scanned or reported."""
    with tempfile.TemporaryDirectory() as tmp:
        root = make_vault(Path(tmp))
        cfg = load_config(root)
        write_note(
            root / ".foam" / "templates" / "new-note.md",
            body="no frontmatter here and name contains FINAL",
        )
        # Also a valid note so the scan isn't empty.
        write_note(root / "1-projects" / "alpha" / "ok.md")
        report = vault_check.walk_vault(root, cfg)
        # No findings should mention .foam
        for f in report.findings:
            assert ".foam" not in f.path, f"protected dir leaked: {f.format_line()}"


def test_protected_root_file_not_flagged():
    with tempfile.TemporaryDirectory() as tmp:
        root = make_vault(Path(tmp))
        cfg = load_config(root)
        # Create a protected root file with no frontmatter — should not be flagged.
        (root / "inbox.md").write_text("# Inbox\n\nNo frontmatter.\n", encoding="utf-8")
        write_note(root / "1-projects" / "alpha" / "ok.md")
        report = vault_check.walk_vault(root, cfg)
        for f in report.findings:
            assert f.path != "inbox.md", f"protected file flagged: {f.format_line()}"


def test_foam_block_orphan_start():
    with tempfile.TemporaryDirectory() as tmp:
        root = make_vault(Path(tmp))
        cfg = load_config(root)
        start = '[//begin]: # "Autogenerated link references for markdown compatibility"'
        write_note(
            root / "1-projects" / "alpha" / "broken-foam.md",
            body=f"---\ntitle: x\ncreated: 2026-04-11\n---\n\nbody\n\n{start}\n[[nowhere]]\n",
        )
        report = vault_check.walk_vault(root, cfg)
        assert "P3" in rules_in(report)


def test_foam_block_wellformed_passes():
    with tempfile.TemporaryDirectory() as tmp:
        root = make_vault(Path(tmp))
        cfg = load_config(root)
        start = '[//begin]: # "Autogenerated link references for markdown compatibility"'
        end = '[//end]: # "Autogenerated link references"'
        write_note(
            root / "1-projects" / "alpha" / "has-foam-block.md",
            body=f"---\ntitle: x\ncreated: 2026-04-11\n---\n\nbody\n\n{start}\n[x]: x \"x\"\n{end}\n",
        )
        report = vault_check.walk_vault(root, cfg)
        assert "P3" not in rules_in(report)


def test_outline_reachability_o1():
    """O1 — notes not reachable from the master outline are flagged when
    outline.enforce_reachability=True. Reachable notes pass."""
    with tempfile.TemporaryDirectory() as tmp:
        root = make_vault(Path(tmp))
        cfg = load_config(root)
        # Opt in to O1 (test config has no outline section by default).
        cfg["outline"] = {
            "master_moc": "outlines",
            "enforce_reachability": True,
            "exempt_dirs": ["_archive"],
        }
        # Master outline at vault root, links to a hub.
        (root / "outlines.md").write_text(
            "---\ntitle: Outlines\ncreated: 2026-04-20\n---\n\n[[my-hub]]\n",
            encoding="utf-8",
        )
        # Hub links to a leaf.
        write_note(
            root / "4-atlas" / "my-hub.md",
            body="---\ntitle: Hub\ncreated: 2026-04-20\n---\n\n[[reachable-leaf]]\n",
        )
        # Reachable leaf — has no outbound link, but is reached from hub.
        write_note(root / "1-projects" / "alpha" / "reachable-leaf.md")
        # Orphan — no inbound link from outlines chain.
        write_note(root / "1-projects" / "alpha" / "orphan-leaf.md")
        # Archived note — exempt from O1.
        write_note(root / "_archive" / "1-projects" / "old" / "archived-note.md")

        report = vault_check.walk_vault(root, cfg)
        o1_paths = paths_for_rule(report, "O1")
        assert any("orphan-leaf.md" in p for p in o1_paths), \
            f"expected orphan-leaf to fire O1; got {o1_paths}"
        assert not any("reachable-leaf.md" in p for p in o1_paths), \
            f"reachable-leaf should not fire O1; got {o1_paths}"
        assert not any("archived-note.md" in p for p in o1_paths), \
            f"archived note should be exempt; got {o1_paths}"
        assert not any("outlines.md" in p for p in o1_paths), \
            f"outlines.md is the root and should not fire; got {o1_paths}"


def test_outline_reachability_disabled_by_default():
    """When outline.enforce_reachability is False (or missing), O1 never fires
    even with orphan notes present."""
    with tempfile.TemporaryDirectory() as tmp:
        root = make_vault(Path(tmp))
        cfg = load_config(root)
        # Default test config has no outline key — leave it absent.
        write_note(root / "1-projects" / "alpha" / "stranded.md")
        report = vault_check.walk_vault(root, cfg)
        assert "O1" not in rules_in(report)


def test_strict_mode_counts_warnings_as_errors():
    """Single-file subfolder is a WARN; under --strict it becomes a failure."""
    with tempfile.TemporaryDirectory() as tmp:
        root = make_vault(Path(tmp))
        cfg = load_config(root)
        write_note(root / "1-projects" / "solo" / "only-note.md")
        report = vault_check.walk_vault(root, cfg)
        # Non-strict: errors should be 0, warnings should include F5
        assert report.errors == []
        assert "F5" in rules_in(report)


# --------------------------------------------------------------------------- #
# Runner
# --------------------------------------------------------------------------- #

def test_rules_exempt_dirs_skip_l3():
    """Slug collisions among paths under `rules.exempt_dirs` must NOT fire L3,
    and a collision between an exempt path and a non-exempt path must NOT fire
    on the non-exempt path (the exempt path doesn't participate)."""
    with tempfile.TemporaryDirectory() as tmp:
        root = make_vault(Path(tmp))
        cfg = load_config(root)
        cfg["rules"] = {"exempt_dirs": ["_archive", "_secretary"]}
        # Allow _secretary as a top-level folder in this fixture.
        cfg["canonical_folders"]["top_level"] = list(
            cfg["canonical_folders"]["top_level"]
        ) + ["_secretary"]

        # Two collisions to exercise:
        # (a) Two files named SKILL.md under _secretary/ — both exempt → no L3.
        write_note(root / "_secretary" / "a" / "SKILL.md")
        write_note(root / "_secretary" / "b" / "SKILL.md")
        # (b) Root CLAUDE.md (non-exempt) + _archive/.../CLAUDE.md (exempt) → no L3.
        write_note(root / "CLAUDE.md")
        write_note(root / "_archive" / "old" / "CLAUDE.md")

        report = vault_check.walk_vault(root, cfg)
        l3_paths = paths_for_rule(report, "L3")
        assert not l3_paths, \
            f"expected no L3 findings; got {l3_paths}"


def test_rules_exempt_dirs_still_fire_l3_on_non_exempt_collisions():
    """A collision between two non-exempt paths must still fire L3, even when
    the config has exempt_dirs defined."""
    with tempfile.TemporaryDirectory() as tmp:
        root = make_vault(Path(tmp))
        cfg = load_config(root)
        cfg["rules"] = {"exempt_dirs": ["_archive", "_secretary"]}
        write_note(root / "1-projects" / "alpha" / "dup.md")
        write_note(root / "2-areas" / "beta" / "dup.md")
        report = vault_check.walk_vault(root, cfg)
        l3_paths = paths_for_rule(report, "L3")
        assert any("alpha/dup.md" in p for p in l3_paths), \
            f"expected L3 on non-exempt alpha/dup.md; got {l3_paths}"
        assert any("beta/dup.md" in p for p in l3_paths), \
            f"expected L3 on non-exempt beta/dup.md; got {l3_paths}"


def test_rules_exempt_dirs_skip_m6():
    """Files under `rules.exempt_dirs` must NOT emit M6 warnings for missing
    recommended frontmatter keys."""
    with tempfile.TemporaryDirectory() as tmp:
        root = make_vault(Path(tmp))
        cfg = load_config(root)
        cfg["rules"] = {"exempt_dirs": ["_archive", "_secretary"]}
        cfg["canonical_folders"]["top_level"] = list(
            cfg["canonical_folders"]["top_level"]
        ) + ["_secretary"]
        # Switch the test fixture from M1-driven required keys to the real
        # recommended-keys mode so M6 fires in the first place.
        cfg["frontmatter"]["required"] = []
        cfg["frontmatter"]["recommended"] = ["title", "created"]

        # Exempt file — no frontmatter — must NOT fire M6.
        write_note(root / "_archive" / "no-fm.md", body="Just a body.\n")
        write_note(root / "_secretary" / "no-fm.md", body="Just a body.\n")
        # Non-exempt file — no frontmatter — MUST fire M6.
        write_note(root / "1-projects" / "alpha" / "no-fm.md", body="Just a body.\n")

        report = vault_check.walk_vault(root, cfg)
        m6_paths = paths_for_rule(report, "M6")
        assert any("alpha/no-fm.md" in p for p in m6_paths), \
            f"expected M6 on non-exempt path; got {m6_paths}"
        assert not any("_archive" in p for p in m6_paths), \
            f"_archive file should be exempt from M6; got {m6_paths}"
        assert not any("_secretary" in p for p in m6_paths), \
            f"_secretary file should be exempt from M6; got {m6_paths}"


def test_append_only_files_skip_m6():
    """Files listed in `append_only.files` must NOT emit M6 warnings."""
    with tempfile.TemporaryDirectory() as tmp:
        root = make_vault(Path(tmp))
        cfg = load_config(root)
        # Remove inbox/todo from protected.files so vault-check actually
        # reads them (the default fixture protects them).
        cfg["protected"]["files"] = []
        cfg["append_only"] = {"files": ["inbox.md", "todo.md"]}
        cfg["frontmatter"]["required"] = []
        cfg["frontmatter"]["recommended"] = ["title", "created"]

        (root / "inbox.md").write_text("# Inbox\n", encoding="utf-8")
        (root / "todo.md").write_text("# Todo\n", encoding="utf-8")
        # Non-exempt root file — MUST fire M6.
        (root / "regular-root-note.md").write_text("# Regular\n", encoding="utf-8")

        report = vault_check.walk_vault(root, cfg)
        m6_paths = paths_for_rule(report, "M6")
        assert any("regular-root-note.md" in p for p in m6_paths), \
            f"expected M6 on regular root note; got {m6_paths}"
        assert not any(p == "inbox.md" for p in m6_paths), \
            f"inbox.md should be exempt from M6; got {m6_paths}"
        assert not any(p == "todo.md" for p in m6_paths), \
            f"todo.md should be exempt from M6; got {m6_paths}"


TESTS = [
    ("clean vault → 0 errors", test_clean_vault_has_zero_findings),
    ("unknown top-level folder → F2", test_unknown_top_level_folder),
    ("missing required frontmatter key → M1", test_missing_required_frontmatter_key),
    ("no frontmatter block at all → M1", test_missing_frontmatter_block_entirely),
    ("forbidden frontmatter key → M2", test_forbidden_frontmatter_key),
    ("invalid created date format → M4", test_invalid_created_date_format),
    ("bad slug grammar → N1", test_slug_grammar_violation),
    ("permissive slugs accepted (v1.8)", test_permissive_slugs_accepted),
    ("slug collision across vault → L3", test_slug_collision_across_vault),
    ("different-case-same-chars does NOT fire N2a", test_case_collision_within_folder_not_triggered_normally),
    ("depth over max_depth → F4", test_depth_over_max),
    ("protected directory is pruned", test_protected_directory_is_pruned),
    ("protected root file not flagged", test_protected_root_file_not_flagged),
    ("broken Foam block (orphan start) → P3", test_foam_block_orphan_start),
    ("well-formed Foam block passes", test_foam_block_wellformed_passes),
    ("orphan from master outline → O1 (when enabled)", test_outline_reachability_o1),
    ("O1 silent when outline.enforce_reachability is False/absent", test_outline_reachability_disabled_by_default),
    ("single-file subfolder → F5 warning", test_strict_mode_counts_warnings_as_errors),
    ("rules.exempt_dirs skip L3 collisions", test_rules_exempt_dirs_skip_l3),
    ("rules.exempt_dirs still fire L3 on non-exempt pairs", test_rules_exempt_dirs_still_fire_l3_on_non_exempt_collisions),
    ("rules.exempt_dirs skip M6 warnings", test_rules_exempt_dirs_skip_m6),
    ("append_only.files skip M6 warnings", test_append_only_files_skip_m6),
]


def main() -> int:
    passed = 0
    failed = 0
    print("vault_check tests:")
    for name, fn in TESTS:
        try:
            fn()
        except AssertionError as e:
            print(f"  FAIL  {name}")
            print(f"        {e}")
            failed += 1
        except Exception as e:
            print(f"  FAIL  {name}  (exception)")
            print(f"        {type(e).__name__}: {e}")
            failed += 1
        else:
            print(f"  PASS  {name}")
            passed += 1
    print()
    print("=" * 50)
    print(f"Total: {passed} passed, {failed} failed")
    return 0 if failed == 0 else 1


if __name__ == "__main__":
    sys.exit(main())
