#!/usr/bin/env python3
"""
build_book_indexes.py — Generate one _INDEX.md per textbook chapter folder.

Walks `<base>/<book>/`, and for each book folder writes a single index file
that lists every chapter as a wikilink and links back to the parent hub.
Re-runnable; idempotent when no chapters changed.

Stdlib only.
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2] / "lib"))
from config_loader import find_vault_root  # noqa: E402

DEFAULT_BASE = "3-resources/anesthesia-refs-md"
DEFAULT_PARENT_HUB = "anesthesia-reference"
DEFAULT_TODAY = "2026-04-20"

_NATURAL_SPLIT = re.compile(r"(\d+)")


def natural_key(name: str) -> list:
    return [int(p) if p.isdigit() else p.lower() for p in _NATURAL_SPLIT.split(name)]


def strip_book_suffix(folder_name: str) -> str:
    return folder_name[:-3] if folder_name.endswith("_md") else folder_name


def render_index(book_dir: Path, parent_hub: str, today: str) -> tuple[Path, str]:
    book_name = strip_book_suffix(book_dir.name)
    index_filename = f"{book_name}_INDEX.md"
    index_path = book_dir / index_filename

    chapters = sorted(
        (p for p in book_dir.glob("*.md") if p.name != index_filename),
        key=lambda p: natural_key(p.stem),
    )

    lines = [
        "---",
        f"title: {book_name} — Index",
        f"created: {today}",
        "type: moc",
        "---",
        "",
        f"# {book_name} — Index",
        "",
        f"All {len(chapters)} chapter(s) in this book. Auto-generated by `build-book-indexes` — do not hand-edit; re-run the feature instead.",
        "",
        f"Parent: [[{parent_hub}]]",
        "",
        "## Chapters",
        "",
    ]
    lines.extend(f"- [[{ch.stem}]]" for ch in chapters)
    lines.append("")
    return index_path, "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description="Generate per-book _INDEX.md files.")
    p.add_argument("--vault-root", type=Path, default=None)
    p.add_argument("--base", default=DEFAULT_BASE)
    p.add_argument("--parent", default=DEFAULT_PARENT_HUB)
    p.add_argument("--today", default=DEFAULT_TODAY)
    p.add_argument("--dry-run", action="store_true")
    args = p.parse_args(argv)

    vault_root = args.vault_root or find_vault_root(Path.cwd())
    base = vault_root / args.base
    if not base.is_dir():
        print(f"error: base folder does not exist: {base}", file=sys.stderr)
        return 2

    book_dirs = sorted(d for d in base.iterdir() if d.is_dir())
    written = unchanged = 0
    for book in book_dirs:
        index_path, content = render_index(book, args.parent, args.today)
        existing = index_path.read_text("utf-8") if index_path.is_file() else None
        if existing == content:
            unchanged += 1
            continue
        if args.dry_run:
            print(f"would write: {index_path.relative_to(vault_root)}")
        else:
            index_path.write_text(content, encoding="utf-8")
            print(f"wrote: {index_path.relative_to(vault_root)}")
        written += 1

    suffix = " (dry-run)" if args.dry_run else ""
    print(f"\nbuild-book-indexes: {written} index(es) written, {unchanged} unchanged.{suffix}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
